---
# tasks file for nginx
- name: Create Nginx CentOS Repository for CentOS 7
  copy:
    src: files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644 
- name: install nginx
  package:
    name: nginx
    state: present
  notify:
  - start nginx
- name: Configure Nginx for PHP-FPM 
  copy:
    src: files/default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart nginx
- name: Make index.php
  lineinfile:
    path: /usr/share/nginx/html/index.php
    owner: 'root'
    group: 'root'
    mode: '0644'
    line: <?php phpinfo(); ?>
    create: yes